//@version=6
indicator("Spread", overlay=true)

int length = input.int(20, "Length", minval=1)
string maType = input.string("SMA", "MA Type", options=["SMA", "EMA"])
float mult = input.float(2.0, minval=0.001, title="StDev Level")

ma(source, length, t) =>
    switch t
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)

float mean = ma(close, length, maType)
float stdev = mult * ta.stdev(close, length)
float upper = mean + stdev
float lower = mean - stdev

plot(mean, "Mean", color=color.orange, display=(display.all - display.price_scale - display.status_line))
p1 = plot(upper, "Upper", color=color.blue, display=(display.all - display.price_scale - display.status_line))
p2 = plot(lower, "Lower", color=color.blue, display=(display.all - display.price_scale - display.status_line))
fill(p1, p2, title = "Background", color=color.rgb(33, 149, 243, 95))
